# -----------------------------------------------------------------------------
# Root Terragrunt — Auto-generated by Self-Service API
# Jira Ticket: INFRA-3003
# Team: platform
# Environment: prod
# -----------------------------------------------------------------------------

locals {
  aws_region  = "eu-central-1"
  environment = "prod"
  project     = "testing"
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "aws" {
      region = "${local.aws_region}"

      default_tags {
        tags = {
          Project     = "${local.project}"
          Environment = "${local.environment}"
          ManagedBy   = "terragrunt"
          Team        = "platform"
          CostCenter  = "CC-PLATFORM-001"
          JiraTicket  = "INFRA-3003"
        }
      }
    }
  EOF
}

remote_state {
  backend = "s3"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    bucket       = "${local.project}-${local.environment}-terraform-state"
    key          = "${path_relative_to_include()}/terraform.tfstate"
    region       = local.aws_region
    encrypt      = true
    use_lockfile = true

    s3_bucket_tags = {
      Project     = local.project
      Environment = local.environment
      ManagedBy   = "terragrunt"
    }
  }
}

inputs = {
  environment = local.environment
  tags = {
    Project    = local.project
    Environment = local.environment
    Team        = "platform"
    CostCenter  = "CC-PLATFORM-001"
    JiraTicket  = "INFRA-3003"
  }
}
